package semantic

import "strings"

// keywordMap maps SQL keywords (uppercase) to their token type.
var keywordMap = map[string]byte{
	// UNION keyword
	"UNION": tokenTypeUnion,

	// SELECT/EXEC group
	"SELECT":  tokenTypeSelect,
	"EXEC":    tokenTypeSelect,
	"EXECUTE": tokenTypeSelect,

	// GROUP BY / ORDER BY
	"GROUP": tokenTypeGroupBy,
	"ORDER": tokenTypeGroupBy,

	// DDL keywords
	"DROP":     tokenTypeDDL,
	"CREATE":   tokenTypeDDL,
	"ALTER":    tokenTypeDDL,
	"TRUNCATE": tokenTypeDDL,

	// Logical operators
	"AND":     tokenTypeLogic,
	"OR":      tokenTypeLogic,
	"NOT":     tokenTypeLogic,
	"XOR":     tokenTypeLogic,
	"BETWEEN": tokenTypeLogic,

	// SQL types
	"INT":       tokenTypeSQLType,
	"INTEGER":   tokenTypeSQLType,
	"BIGINT":    tokenTypeSQLType,
	"SMALLINT":  tokenTypeSQLType,
	"TINYINT":   tokenTypeSQLType,
	"FLOAT":     tokenTypeSQLType,
	"DOUBLE":    tokenTypeSQLType,
	"DECIMAL":   tokenTypeSQLType,
	"NUMERIC":   tokenTypeSQLType,
	"REAL":      tokenTypeSQLType,
	"VARCHAR":   tokenTypeSQLType,
	"CHAR":      tokenTypeSQLType,
	"NCHAR":     tokenTypeSQLType,
	"NVARCHAR":  tokenTypeSQLType,
	"TEXT":      tokenTypeSQLType,
	"BLOB":      tokenTypeSQLType,
	"DATE":      tokenTypeSQLType,
	"TIME":      tokenTypeSQLType,
	"DATETIME":  tokenTypeSQLType,
	"TIMESTAMP": tokenTypeSQLType,
	"BOOLEAN":   tokenTypeSQLType,
	"BOOL":      tokenTypeSQLType,
	"CLOB":      tokenTypeSQLType,

	// Regular SQL keywords
	"FROM":               tokenTypeKeyword,
	"WHERE":              tokenTypeKeyword,
	"INTO":               tokenTypeKeyword,
	"VALUES":             tokenTypeKeyword,
	"SET":                tokenTypeKeyword,
	"INSERT":             tokenTypeKeyword,
	"UPDATE":             tokenTypeKeyword,
	"DELETE":             tokenTypeKeyword,
	"TABLE":              tokenTypeKeyword,
	"DATABASE":           tokenTypeKeyword,
	"INDEX":              tokenTypeKeyword,
	"VIEW":               tokenTypeKeyword,
	"HAVING":             tokenTypeKeyword,
	"LIMIT":              tokenTypeKeyword,
	"OFFSET":             tokenTypeKeyword,
	"JOIN":               tokenTypeKeyword,
	"INNER":              tokenTypeKeyword,
	"OUTER":              tokenTypeKeyword,
	"LEFT":               tokenTypeKeyword,
	"RIGHT":              tokenTypeKeyword,
	"CROSS":              tokenTypeKeyword,
	"ON":                 tokenTypeKeyword,
	"AS":                 tokenTypeKeyword,
	"IN":                 tokenTypeKeyword,
	"EXISTS":             tokenTypeKeyword,
	"LIKE":               tokenTypeKeyword,
	"IS":                 tokenTypeKeyword,
	"NULL":               tokenTypeKeyword,
	"TRUE":               tokenTypeKeyword,
	"FALSE":              tokenTypeKeyword,
	"CASE":               tokenTypeKeyword,
	"WHEN":               tokenTypeKeyword,
	"THEN":               tokenTypeKeyword,
	"ELSE":               tokenTypeKeyword,
	"END":                tokenTypeKeyword,
	"BY":                 tokenTypeKeyword,
	"ASC":                tokenTypeKeyword,
	"DESC":               tokenTypeKeyword,
	"ALL":                tokenTypeKeyword,
	"DISTINCT":           tokenTypeKeyword,
	"TOP":                tokenTypeKeyword,
	"DECLARE":            tokenTypeKeyword,
	"BEGIN":              tokenTypeKeyword,
	"COMMIT":             tokenTypeKeyword,
	"ROLLBACK":           tokenTypeKeyword,
	"GRANT":              tokenTypeKeyword,
	"REVOKE":             tokenTypeKeyword,
	"IF":                 tokenTypeKeyword,
	"PROCEDURE":          tokenTypeKeyword,
	"FUNCTION":           tokenTypeKeyword,
	"TRIGGER":            tokenTypeKeyword,
	"REPLACE":            tokenTypeKeyword,
	"LOAD":               tokenTypeKeyword,
	"OUTFILE":            tokenTypeKeyword,
	"INFILE":             tokenTypeKeyword,
	"SLEEP":              tokenTypeKeyword,
	"BENCHMARK":          tokenTypeKeyword,
	"WAITFOR":            tokenTypeKeyword,
	"DELAY":              tokenTypeKeyword,
	"SCHEMA":             tokenTypeKeyword,
	"CAST":               tokenTypeKeyword,
	"CONVERT":            tokenTypeKeyword,
	"INFORMATION_SCHEMA": tokenTypeKeyword,
	"EXTRACTVALUE":       tokenTypeKeyword,
	"UPDATEXML":          tokenTypeKeyword,
	"CONCAT":             tokenTypeKeyword,
	"SUBSTRING":          tokenTypeKeyword,
	"SUBSTR":             tokenTypeKeyword,
	"ASCII":              tokenTypeKeyword,
	"ORD":                tokenTypeKeyword,
	"CHAR_LENGTH":        tokenTypeKeyword,
	"LENGTH":             tokenTypeKeyword,
	"COUNT":              tokenTypeKeyword,
	"SUM":                tokenTypeKeyword,
	"AVG":                tokenTypeKeyword,
	"MAX":                tokenTypeKeyword,
	"MIN":                tokenTypeKeyword,
	"COALESCE":           tokenTypeKeyword,
	"IFNULL":             tokenTypeKeyword,
	"NULLIF":             tokenTypeKeyword,
	"HEX":                tokenTypeKeyword,
	"UNHEX":              tokenTypeKeyword,
	"MD5":                tokenTypeKeyword,
	"SHA1":               tokenTypeKeyword,
	"SHA2":               tokenTypeKeyword,
	"RAND":               tokenTypeKeyword,
	"FLOOR":              tokenTypeKeyword,
	"CEIL":               tokenTypeKeyword,
	"CEILING":            tokenTypeKeyword,
	"ABS":                tokenTypeKeyword,
	"MOD":                tokenTypeKeyword,
	"POWER":              tokenTypeKeyword,
	"ROUND":              tokenTypeKeyword,
	"SIGN":               tokenTypeKeyword,
	"SQRT":               tokenTypeKeyword,
	"UPPER":              tokenTypeKeyword,
	"LOWER":              tokenTypeKeyword,
	"TRIM":               tokenTypeKeyword,
	"LTRIM":              tokenTypeKeyword,
	"RTRIM":              tokenTypeKeyword,
	"REVERSE":            tokenTypeKeyword,
	"REPEAT":             tokenTypeKeyword,
	"SPACE":              tokenTypeKeyword,
	"REPLACE_FUNC":       tokenTypeKeyword,
	"POSITION":           tokenTypeKeyword,
	"LOCATE":             tokenTypeKeyword,
	"INSTR":              tokenTypeKeyword,
	"LCASE":              tokenTypeKeyword,
	"UCASE":              tokenTypeKeyword,
	"MID":                tokenTypeKeyword,
	"LEFT_FUNC":          tokenTypeKeyword,
	"RIGHT_FUNC":         tokenTypeKeyword,
	"VERSION":            tokenTypeKeyword,
	"USER":               tokenTypeKeyword,
	"CURRENT_USER":       tokenTypeKeyword,
	"SESSION_USER":       tokenTypeKeyword,
	"SYSTEM_USER":        tokenTypeKeyword,
	"DATABASE_FUNC":      tokenTypeKeyword,
	"SCHEMA_FUNC":        tokenTypeKeyword,
	"ROW_COUNT":          tokenTypeKeyword,
	"FOUND_ROWS":         tokenTypeKeyword,
	"LAST_INSERT_ID":     tokenTypeKeyword,
	"GROUP_CONCAT":       tokenTypeKeyword,
	"MAKE_SET":           tokenTypeKeyword,
	"EXPORT_SET":         tokenTypeKeyword,
	"LOAD_FILE":          tokenTypeKeyword,
	"CHAR_FUNC":          tokenTypeKeyword,
}

// lookupKeyword returns the token type for a word; defaults to bareword.
func lookupKeyword(word string) byte {
	upper := strings.ToUpper(word)
	if ttype, ok := keywordMap[upper]; ok {
		return ttype
	}
	return tokenTypeBareword
}
